# Generated by Django 4.2.6 on 2023-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fechaReserva', models.DateField()),
                ('hora', models.TimeField()),
                ('NumPersonas', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('observacion', models.CharField(max_length=150)),
            ],
        ),
    ]
