# Generated by Django 4.2.6 on 2023-12-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscritos',
            old_name='idinstitucion',
            new_name='institucion',
        ),
    ]
